Substitute openbeans for java.beans to support Android
tcheeric/nostr-java pull request #122
Opened 2024-03-26 02:06 UTC by kuiperanon

Created for this issue: https://github.com/tcheeric/nostr-java/issues/118

It builds for me and solves the problem when using the library in my Android app. More details in the issue page.

2024-03-26 21:03 UTC, tcheeric commented
Please do not hard-code dependencies' versions, use a property instead, e.g. ```${openbeans.version}```
The property should be defined in the main project's pom.
Thanks.

2024-03-26 21:06 UTC, tcheeric requested changes

2024-03-26 21:06 UTC, tcheeric commented on nostr-java-event/pom.xml
The version should not be hard-coded. Use a property instead. See comment in the PR. Thanks.

2024-03-27 00:06 UTC, kuiperanon commented on nostr-java-event/pom.xml
Fixed with 683078169c599cd5ce626603037359ca87ff71d8

2024-04-03 13:03 UTC, merged